/* vocab.js — the word bank.
 *
 * Every entry is [hanzi, pinyin, english, level], where level is 1..4 from
 * core to advanced. The list is not a general dictionary: it is the words
 * that actually occur in these 4,228 questions, chosen by frequency over the
 * corpus and then glossed by hand, so a word you meet on a card is a word
 * that is in here and a word in here is one you will meet.
 *
 * It doubles as the segmenter's dictionary. core.js walks each Chinese
 * sentence with a longest-match-first pass over these keys, which is why the
 * multi-character entries matter as much as the glosses: 还是 has to win over
 * 还 + 是, or every A-or-B question breaks into nonsense.
 *
 * Ordering inside the array is irrelevant; it is indexed on load.
 */
window.__VOCAB__ = {
  version: 1,
  levels: ["Core", "Common", "Wider", "Advanced"],
  w: [

  /* ---- pronouns, people ---- */
  ["你","nǐ","you",1],["您","nín","you (polite)",2],["我","wǒ","I, me",1],
  ["他","tā","he, him",1],["她","tā","she, her",1],["它","tā","it",1],
  ["我们","wǒ men","we, us",1],["你们","nǐ men","you (plural)",1],
  ["他们","tā men","they, them",1],["自己","zì jǐ","oneself, own",1],
  ["别人","bié rén","other people, someone else",1],["人","rén","person, people",1],
  ["大家","dà jiā","everyone",2],["谁","shuí","who",1],["某人","mǒu rén","somebody",3],
  ["对方","duì fāng","the other party, the other person",3],
  ["人们","rén men","people",2],["个人","gè rén","individual, personal",2],

  /* ---- question words ---- */
  ["什么","shén me","what",1],["为什么","wèi shén me","why",1],
  ["怎么","zěn me","how",1],["怎样","zěn yàng","how, in what way",2],
  ["怎么样","zěn me yàng","how about it, what's it like",1],
  ["哪","nǎ","which",1],["哪个","nǎ ge","which one",1],["哪些","nǎ xiē","which ones",1],
  ["哪里","nǎ lǐ","where",1],["什么时候","shén me shí hòu","when",1],
  ["多少","duō shǎo","how many, how much",1],["多久","duō jiǔ","how long (time)",2],
  ["几","jǐ","how many (small number)",1],["吗","ma","(yes/no question marker)",1],
  ["呢","ne","(follow-up question particle)",1],["吧","ba","(suggestion / supposition particle)",2],
  ["是否","shì fǒu","whether or not",3],["是不是","shì bú shì","is it or isn't it",2],

  /* ---- core verbs ---- */
  ["是","shì","to be",1],["有","yǒu","to have, there is",1],["没有","méi yǒu","not have, there isn't",1],
  ["会","huì","will; to know how to",1],["能","néng","can, be able to",1],["可以","kě yǐ","may, can",1],
  ["要","yào","to want; will",1],["想","xiǎng","to think; to want to",1],
  ["觉得","jué de","to feel, to think",1],["认为","rèn wéi","to consider, to hold that",2],
  ["相信","xiāng xìn","to believe",2],["知道","zhī dào","to know (a fact)",1],
  ["认识","rèn shí","to know (a person), to be acquainted with",1],
  ["了解","liǎo jiě","to understand, to be familiar with",2],
  ["明白","míng bai","to understand, to see",2],["记得","jì de","to remember",1],
  ["忘记","wàng jì","to forget",2],["喜欢","xǐ huān","to like",1],["爱","ài","to love",1],
  ["讨厌","tǎo yàn","to dislike, to find annoying",2],["害怕","hài pà","to be afraid of",2],
  ["希望","xī wàng","to hope; hope",1],["愿意","yuàn yì","to be willing to",2],
  ["宁愿","nìng yuàn","would rather",3],["需要","xū yào","to need",1],
  ["应该","yīng gāi","should, ought to",1],["必须","bì xū","must, have to",2],
  ["做","zuò","to do, to make",1],["作","zuò","to do, to act as",2],["去","qù","to go",1],
  ["来","lái","to come",1],["回","huí","to return",1],["到","dào","to arrive; to (a point)",1],
  ["看","kàn","to look, to watch, to read",1],["听","tīng","to listen",1],["说","shuō","to say, to speak",1],
  ["讲","jiǎng","to speak, to tell",2],["告诉","gào sù","to tell (someone)",1],
  ["问","wèn","to ask",1],["回答","huí dá","to answer",2],["聊","liáo","to chat",2],
  ["谈","tán","to talk about, to discuss",2],["写","xiě","to write",1],["读","dú","to read",1],
  ["学","xué","to learn, to study",1],["学习","xué xí","to study, to learn",1],
  ["教","jiāo","to teach",2],["用","yòng","to use",1],["买","mǎi","to buy",1],["卖","mài","to sell",2],
  ["吃","chī","to eat",1],["喝","hē","to drink",1],["睡","shuì","to sleep",1],
  ["住","zhù","to live, to reside",1],["走","zǒu","to walk, to leave",1],["跑","pǎo","to run",1],
  ["开","kāi","to open; to drive",1],["关","guān","to close; to turn off",1],
  ["给","gěi","to give; for",1],["拿","ná","to take, to hold",2],["带","dài","to bring, to carry",2],
  ["找","zhǎo","to look for",1],["等","děng","to wait",1],["帮","bāng","to help",1],
  ["帮助","bāng zhù","to help; help",2],["选","xuǎn","to choose",2],["选择","xuǎn zé","to choose; choice",2],
  ["决定","jué dìng","to decide; decision",2],["改变","gǎi biàn","to change",2],
  ["变","biàn","to change, to become",2],["成为","chéng wéi","to become",2],
  ["发生","fā shēng","to happen, to occur",2],["出现","chū xiàn","to appear, to emerge",3],
  ["发现","fā xiàn","to discover, to find",2],["遇到","yù dào","to run into, to encounter",2],
  ["经历","jīng lì","to experience; experience",2],["参加","cān jiā","to take part in, to attend",2],
  ["尝试","cháng shì","to try, to attempt",3],["试","shì","to try",2],
  ["开始","kāi shǐ","to begin, to start",1],["结束","jié shù","to end, to finish",2],
  ["继续","jì xù","to continue",2],["停","tíng","to stop",2],
  ["接受","jiē shòu","to accept",2],["拒绝","jù jué","to refuse, to turn down",3],
  ["同意","tóng yì","to agree",2],["反对","fǎn duì","to oppose, to object to",3],
  ["支持","zhī chí","to support",2],["允许","yǔn xǔ","to allow, to permit",3],
  ["处理","chǔ lǐ","to deal with, to handle",3],["解决","jiě jué","to solve, to resolve",2],
  ["影响","yǐng xiǎng","to affect; influence",2],["表达","biǎo dá","to express",3],
  ["描述","miáo shù","to describe",3],["形容","xíng róng","to describe, to characterise",3],
  ["感到","gǎn dào","to feel (an emotion)",2],["感觉","gǎn jué","to feel; feeling",2],
  ["发展","fā zhǎn","to develop; development",3],["创造","chuàng zào","to create",3],
  ["拥有","yōng yǒu","to own, to possess",3],["失去","shī qù","to lose",3],
  ["得到","dé dào","to get, to obtain",2],["实现","shí xiàn","to achieve, to realise",3],
  ["保持","bǎo chí","to keep, to maintain",3],["联系","lián xì","to contact; connection",3],
  ["相处","xiāng chǔ","to get along with",3],["面对","miàn duì","to face, to confront",3],
  ["考虑","kǎo lǜ","to consider",3],["计划","jì huà","to plan; plan",2],
  ["期待","qī dài","to look forward to",3],["担心","dān xīn","to worry",2],
  ["后悔","hòu huǐ","to regret",3],["原谅","yuán liàng","to forgive",3],
  ["承认","chéng rèn","to admit, to acknowledge",3],

  /* ---- adverbs, connectives, particles ---- */
  ["的","de","(possessive / modifier particle)",1],["了","le","(completed action particle)",1],
  ["着","zhe","(ongoing state particle)",2],["过","guò","(experienced-before particle)",1],
  ["不","bù","not",1],["没","méi","not (have)",1],["很","hěn","very",1],["太","tài","too, excessively",1],
  ["最","zuì","most, -est",1],["更","gèng","more, even more",1],["非常","fēi cháng","extremely",1],
  ["比较","bǐ jiào","relatively, fairly; to compare",2],["有点","yǒu diǎn","a bit, somewhat",2],
  ["还","hái","still, also",1],["还是","hái shì","or (in a question); still",1],
  ["或","huò","or",1],["或者","huò zhě","or",1],["和","hé","and, with",1],["跟","gēn","with, and",1],
  ["与","yǔ","and, with (formal)",3],["但","dàn","but",1],["但是","dàn shì","but",1],
  ["可是","kě shì","but",1],["不过","bú guò","however",2],["虽然","suī rán","although",2],
  ["因为","yīn wèi","because",1],["所以","suǒ yǐ","so, therefore",1],
  ["如果","rú guǒ","if",1],["要是","yào shì","if",2],["的话","de huà","if (clause-final)",2],
  ["那么","nà me","then; so",1],["就","jiù","then, right away",1],["才","cái","only then",2],
  ["也","yě","also",1],["都","dōu","all, both",1],["只","zhǐ","only",1],["只有","zhǐ yǒu","only if, only",2],
  ["除了","chú le","apart from, except",2],["而且","ér qiě","moreover",2],
  ["其实","qí shí","actually, in fact",2],["当然","dāng rán","of course",2],
  ["一定","yí dìng","definitely, certainly",2],["可能","kě néng","maybe; possible",1],
  ["也许","yě xǔ","perhaps",2],["大概","dà gài","roughly, probably",2],
  ["通常","tōng cháng","usually",2],["经常","jīng cháng","often",2],["常常","cháng cháng","often",2],
  ["总是","zǒng shì","always",2],["从来","cóng lái","ever, always (with 不/没)",2],
  ["有时","yǒu shí","sometimes",2],["偶尔","ǒu ěr","occasionally",3],
  ["已经","yǐ jīng","already",1],["曾经","céng jīng","once, formerly",3],
  ["正在","zhèng zài","in the middle of (doing)",2],["马上","mǎ shàng","right away",2],
  ["终于","zhōng yú","finally, at last",2],["突然","tū rán","suddenly",2],
  ["一直","yì zhí","all along, continuously",2],["完全","wán quán","completely",2],
  ["真的","zhēn de","really",1],["真正","zhēn zhèng","genuine, truly",3],
  ["特别","tè bié","especially; special",2],["尤其","yóu qí","especially",3],
  ["几乎","jī hū","almost",2],["至少","zhì shǎo","at least",2],["甚至","shèn zhì","even (to the point of)",3],
  ["然后","rán hòu","then, afterwards",1],["最后","zuì hòu","finally, last",1],
  ["首先","shǒu xiān","first of all",2],["其次","qí cì","secondly",3],
  ["另外","lìng wài","besides, in addition",3],["比如","bǐ rú","for example",2],
  ["例如","lì rú","for example",3],["总之","zǒng zhī","in short, all in all",3],
  ["因此","yīn cǐ","therefore",3],["于是","yú shì","and so, thereupon",3],
  ["其他","qí tā","other",2],["任何","rèn hé","any",2],["所有","suǒ yǒu","all",2],
  ["每","měi","every",1],["某","mǒu","a certain",3],["各","gè","each, various",3],

  /* ---- time ---- */
  ["时候","shí hòu","time, moment",1],["时间","shí jiān","time",1],["小时候","xiǎo shí hòu","childhood, when young",2],
  ["现在","xiàn zài","now",1],["以前","yǐ qián","before, in the past",1],["以后","yǐ hòu","after, later",1],
  ["过去","guò qù","the past",2],["未来","wèi lái","the future",2],["将来","jiāng lái","the future",3],
  ["今天","jīn tiān","today",1],["明天","míng tiān","tomorrow",1],["昨天","zuó tiān","yesterday",1],
  ["年","nián","year",1],["月","yuè","month; moon",1],["天","tiān","day; sky",1],["周","zhōu","week",1],
  ["星期","xīng qī","week",1],["周末","zhōu mò","weekend",1],["每天","měi tiān","every day",1],
  ["年轻","nián qīng","young",2],["年纪","nián jì","age",2],["岁","suì","years old",1],
  ["童年","tóng nián","childhood",2],["成年","chéng nián","adulthood; to come of age",3],
  ["第一次","dì yī cì","the first time",1],["最近","zuì jìn","recently, lately",2],
  ["当时","dāng shí","at that time",2],["后来","hòu lái","later on, afterwards",2],
  ["一辈子","yí bèi zi","a whole lifetime",3],["人生","rén shēng","life (a human life)",2],
  ["生活","shēng huó","life, to live",1],["日子","rì zi","days, life",2],

  /* ---- family & relationships ---- */
  ["家","jiā","home, family",1],["家人","jiā rén","family members",1],["家庭","jiā tíng","family, household",2],
  ["父母","fù mǔ","parents",1],["父亲","fù qīn","father",2],["母亲","mǔ qīn","mother",2],
  ["爸爸","bà bà","dad",1],["妈妈","mā mā","mum",1],["孩子","hái zi","child, children",1],
  ["儿子","ér zi","son",1],["女儿","nǚ ér","daughter",1],["兄弟","xiōng dì","brothers",2],
  ["姐妹","jiě mèi","sisters",2],["兄弟姐妹","xiōng dì jiě mèi","siblings",2],
  ["祖父母","zǔ fù mǔ","grandparents",3],["亲戚","qīn qī","relatives",3],
  ["朋友","péng yǒu","friend",1],["好友","hǎo yǒu","close friend",2],
  ["伴侣","bàn lǚ","partner (in a relationship)",3],["爱人","ài ren","spouse, partner",3],
  ["男朋友","nán péng yǒu","boyfriend",1],["女朋友","nǚ péng yǒu","girlfriend",1],
  ["结婚","jié hūn","to get married",2],["婚姻","hūn yīn","marriage",3],
  ["离婚","lí hūn","to divorce",3],["约会","yuē huì","a date; to go on a date",2],
  ["恋爱","liàn ài","romance, to be in love",3],["关系","guān xì","relationship, connection",2],
  ["感情","gǎn qíng","feelings, affection",3],["爱情","ài qíng","romantic love",3],
  ["信任","xìn rèn","to trust; trust",3],["陪","péi","to accompany, to keep company",2],
  ["照顾","zhào gù","to look after",2],["同事","tóng shì","colleague",2],
  ["邻居","lín jū","neighbour",2],["同学","tóng xué","classmate",1],
  ["长辈","zhǎng bèi","elder, senior family member",4],

  /* ---- feelings & personality ---- */
  ["开心","kāi xīn","happy",1],["高兴","gāo xìng","glad, pleased",1],
  ["快乐","kuài lè","happy, joyful",1],["幸福","xìng fú","happiness, contentment",2],
  ["难过","nán guò","sad",2],["伤心","shāng xīn","heartbroken, upset",2],
  ["生气","shēng qì","angry",1],["紧张","jǐn zhāng","nervous, tense",2],
  ["放松","fàng sōng","relaxed, to relax",2],["累","lèi","tired",1],
  ["孤独","gū dú","lonely",3],["尴尬","gān gà","awkward, embarrassed",3],
  ["骄傲","jiāo ào","proud",3],["感动","gǎn dòng","moved, touched",3],
  ["害羞","hài xiū","shy",2],["自信","zì xìn","confident; confidence",3],
  ["性格","xìng gé","personality, character",2],["脾气","pí qì","temper",3],
  ["习惯","xí guàn","habit; to be used to",2],["态度","tài dù","attitude",3],
  ["优点","yōu diǎn","strength, good point",3],["缺点","quē diǎn","shortcoming, flaw",3],
  ["善良","shàn liáng","kind-hearted",3],["诚实","chéng shí","honest",3],
  ["耐心","nài xīn","patience; patient",3],["幽默","yōu mò","humour; humorous",3],
  ["安静","ān jìng","quiet",2],["外向","wài xiàng","outgoing, extroverted",4],
  ["内向","nèi xiàng","introverted",4],["社交","shè jiāo","social, socialising",3],

  /* ---- work, school, money ---- */
  ["工作","gōng zuò","work, job",1],["职业","zhí yè","profession, career",3],
  ["事业","shì yè","career, undertaking",3],["公司","gōng sī","company",1],
  ["老板","lǎo bǎn","boss",2],["同行","tóng háng","people in the same trade",4],
  ["上班","shàng bān","to go to work",1],["下班","xià bān","to finish work",1],
  ["加班","jiā bān","to work overtime",2],["退休","tuì xiū","to retire",3],
  ["面试","miàn shì","job interview",3],["简历","jiǎn lì","CV, résumé",4],
  ["工资","gōng zī","wage, salary",2],["收入","shōu rù","income",3],
  ["赚","zhuàn","to earn",2],["花","huā","to spend; flower",1],["存","cún","to save, to store",2],
  ["钱","qián","money",1],["价格","jià gé","price",2],["贵","guì","expensive",1],
  ["便宜","pián yi","cheap",1],["值得","zhí de","to be worth",2],
  ["贫穷","pín qióng","poor, poverty",3],["富有","fù yǒu","wealthy",3],
  ["学校","xué xiào","school",1],["大学","dà xué","university",1],
  ["小学","xiǎo xué","primary school",1],["中学","zhōng xué","secondary school",1],
  ["高中","gāo zhōng","upper secondary school",2],["初中","chū zhōng","lower secondary school",2],
  ["专业","zhuān yè","major, field of study; professional",2],
  ["老师","lǎo shī","teacher",1],["学生","xué shēng","student",1],
  ["考试","kǎo shì","exam",1],["成绩","chéng jì","grades, results",2],
  ["教育","jiào yù","education",2],["知识","zhī shí","knowledge",2],
  ["技能","jì néng","skill",3],["能力","néng lì","ability",2],
  ["擅长","shàn cháng","to be good at",3],["练习","liàn xí","to practise; practice",2],
  ["努力","nǔ lì","to work hard; effort",2],["成功","chéng gōng","success; to succeed",2],
  ["失败","shī bài","failure; to fail",2],["机会","jī huì","opportunity, chance",2],
  ["压力","yā lì","pressure, stress",2],["目标","mù biāo","goal, target",3],
  ["梦想","mèng xiǎng","dream (aspiration)",2],["理想","lǐ xiǎng","ideal",3],

  /* ---- everyday life & things ---- */
  ["东西","dōng xī","thing, stuff",1],["事情","shì qíng","matter, thing (event)",1],
  ["事","shì","matter, affair",1],["问题","wèn tí","question, problem",1],
  ["情况","qíng kuàng","situation",2],["方式","fāng shì","way, manner",2],
  ["方法","fāng fǎ","method",2],["办法","bàn fǎ","way, solution",2],
  ["地方","dì fāng","place",1],["房子","fáng zi","house",1],["房间","fáng jiān","room",1],
  ["城市","chéng shì","city",1],["国家","guó jiā","country",1],["世界","shì jiè","world",1],
  ["家乡","jiā xiāng","hometown",2],["附近","fù jìn","nearby",2],
  ["路","lù","road, way",1],["车","chē","vehicle, car",1],["开车","kāi chē","to drive",1],
  ["飞机","fēi jī","aeroplane",1],["火车","huǒ chē","train",1],["旅行","lǚ xíng","to travel; travel",2],
  ["旅游","lǚ yóu","tourism, to travel",2],["假期","jià qī","holiday, break",2],
  ["食物","shí wù","food",2],["饭","fàn","meal, rice",1],["做饭","zuò fàn","to cook",1],
  ["餐厅","cān tīng","restaurant",1],["味道","wèi dào","taste, flavour",2],
  ["咖啡","kā fēi","coffee",1],["茶","chá","tea",1],["酒","jiǔ","alcohol, wine",1],
  ["衣服","yī fú","clothes",1],["手机","shǒu jī","mobile phone",1],
  ["电脑","diàn nǎo","computer",1],["网络","wǎng luò","the internet, network",2],
  ["网上","wǎng shàng","online",2],["电视","diàn shì","television",1],
  ["电影","diàn yǐng","film, movie",1],["音乐","yīn yuè","music",1],
  ["书","shū","book",1],["故事","gù shì","story",1],["新闻","xīn wén","news",2],
  ["节目","jié mù","programme, show",2],["游戏","yóu xì","game",1],
  ["运动","yùn dòng","sport, exercise",1],["体育","tǐ yù","physical education, sport",2],
  ["爱好","ài hào","hobby",2],["兴趣","xìng qù","interest",2],
  ["乐趣","lè qù","fun, enjoyment",3],["体验","tǐ yàn","experience (first-hand)",3],
  ["照片","zhào piàn","photo",1],["礼物","lǐ wù","gift",1],
  ["动物","dòng wù","animal",1],["宠物","chǒng wù","pet",2],
  ["天气","tiān qì","weather",1],["自然","zì rán","nature; natural",2],

  /* ---- body, health, life events ---- */
  ["身体","shēn tǐ","body, health",1],["健康","jiàn kāng","health; healthy",1],
  ["生病","shēng bìng","to fall ill",1],["医生","yī shēng","doctor",1],
  ["医院","yī yuàn","hospital",1],["药","yào","medicine",1],
  ["睡觉","shuì jiào","to sleep",1],["休息","xiū xī","to rest",1],
  ["锻炼","duàn liàn","to exercise",2],["饮食","yǐn shí","diet",3],
  ["死","sǐ","to die",1],["死亡","sǐ wáng","death",3],["去世","qù shì","to pass away",3],
  ["葬礼","zàng lǐ","funeral",4],["悲伤","bēi shāng","grief, sorrow",3],
  ["安全","ān quán","safe; safety",2],["危险","wēi xiǎn","dangerous; danger",2],
  ["痛苦","tòng kǔ","pain, suffering",3],["治疗","zhì liáo","treatment; to treat",3],

  /* ---- society, belief, politics ---- */
  ["社会","shè huì","society",2],["政府","zhèng fǔ","government",2],
  ["政治","zhèng zhì","politics",3],["法律","fǎ lǜ","law",2],
  ["制度","zhì dù","system, institution",3],["权利","quán lì","right (entitlement)",3],
  ["责任","zé rèn","responsibility",3],["自由","zì yóu","freedom",2],
  ["平等","píng děng","equality",3],["公平","gōng píng","fair",3],
  ["公共","gōng gòng","public",3],["文化","wén huà","culture",2],
  ["传统","chuán tǒng","tradition; traditional",2],["宗教","zōng jiào","religion",3],
  ["信仰","xìn yǎng","faith, belief",3],["灵性","líng xìng","spirituality",4],
  ["上帝","shàng dì","God",3],["祈祷","qí dǎo","to pray",4],
  ["道德","dào dé","morality",3],["价值","jià zhí","value",3],
  ["价值观","jià zhí guān","values",3],["意义","yì yì","meaning, significance",3],
  ["观点","guān diǎn","point of view",3],["意见","yì jiàn","opinion",2],
  ["看法","kàn fǎ","view, opinion",2],["犯罪","fàn zuì","crime; to commit a crime",3],
  ["战争","zhàn zhēng","war",3],["和平","hé píng","peace",3],
  ["环境","huán jìng","environment",2],["气候","qì hòu","climate",3],
  ["科技","kē jì","technology",3],["科学","kē xué","science",2],
  ["历史","lì shǐ","history",2],["种族","zhǒng zú","race, ethnicity",4],
  ["性别","xìng bié","gender",3],["男性","nán xìng","male",3],["女性","nǚ xìng","female",3],
  ["总统","zǒng tǒng","president (of a country)",3],["领导","lǐng dǎo","leader; to lead",3],

  /* ---- descriptive ---- */
  ["好","hǎo","good",1],["坏","huài","bad, broken",1],["大","dà","big",1],["小","xiǎo","small",1],
  ["多","duō","many, much",1],["少","shǎo","few, little",1],["长","cháng","long",1],
  ["短","duǎn","short",1],["新","xīn","new",1],["旧","jiù","old (of things)",1],
  ["难","nán","difficult",1],["容易","róng yì","easy",1],["简单","jiǎn dān","simple",1],
  ["复杂","fù zá","complicated",2],["重要","zhòng yào","important",1],
  ["有趣","yǒu qù","interesting, fun",2],["无聊","wú liáo","boring",2],
  ["奇怪","qí guài","strange",2],["特殊","tè shū","special, particular",3],
  ["普通","pǔ tōng","ordinary",2],["一般","yì bān","generally; ordinary",2],
  ["相同","xiāng tóng","the same",3],["不同","bù tóng","different",2],
  ["糟糕","zāo gāo","terrible, awful",3],["严重","yán zhòng","serious, severe",3],
  ["合适","hé shì","suitable",2],["适合","shì hé","to suit, to be suitable for",2],
  ["满意","mǎn yì","satisfied",2],["舒服","shū fú","comfortable",1],
  ["漂亮","piào liang","pretty",1],["美","měi","beautiful",1],
  ["聪明","cōng míng","clever",1],["笨","bèn","stupid",2],
  ["主要","zhǔ yào","main, principal",2],
  ["部分","bù fen","part, portion",2],["全部","quán bù","all, whole",2],
  ["其中","qí zhōng","among them, of which",3],["之间","zhī jiān","between",3],
  ["方面","fāng miàn","aspect, respect",2],["种","zhǒng","kind, type",1],
  ["类","lèi","category, kind",2],["样","yàng","kind, appearance",1],

  /* ---- measure words & common bits ---- */
  ["个","gè","(general measure word)",1],["位","wèi","(polite measure word for people)",2],
  ["件","jiàn","(measure word for matters, clothes)",1],["次","cì","time, occasion",1],
  ["本","běn","(measure word for books)",1],["部","bù","(measure word for films, works)",2],
  ["段","duàn","section, stretch (of time, text)",2],["句","jù","(measure word for sentences)",2],
  ["点","diǎn","point, a bit; o'clock",1],["些","xiē","some",1],
  ["中","zhōng","middle, in",1],["里","lǐ","inside",1],["上","shàng","on, above; previous",1],
  ["下","xià","under, below; next",1],["前","qián","front, before",1],["后","hòu","behind, after",1],
  ["在","zài","at, in; to be at",1],["从","cóng","from",1],["对","duì","towards; correct",1],
  ["把","bǎ","(object-fronting particle)",2],["被","bèi","by (passive marker)",2],
  ["为","wèi","for",1],["向","xiàng","towards",2],
  ["关于","guān yú","about, concerning",2],["对于","duì yú","regarding",3],
  ["来说","lái shuō","as far as ... is concerned",2],["之一","zhī yī","one of",3],
  ["以","yǐ","with, by means of",3],["于","yú","in, at (formal)",3],
/* ---- number + measure word, the commonest shape in the corpus ---- */
  ["一","yī","one; a",1],["两","liǎng","two (of something)",1],["三","sān","three",1],
  ["十","shí","ten",1],["半","bàn","half",1],["第一","dì yī","first",1],
  ["一个","yí gè","one, a (general)",1],["一个人","yí gè rén","one person; alone",1],
  ["一次","yí cì","once, one time",1],["一种","yì zhǒng","a kind of",1],
  ["一件","yí jiàn","one (matter, item of clothing)",1],["一件事","yí jiàn shì","one thing (that happened)",1],
  ["一起","yì qǐ","together",1],["一段","yí duàn","a stretch of, a period of",2],
  ["一位","yí wèi","one (person, polite)",2],["一下","yí xià","briefly, a moment",1],
  ["一部","yí bù","one (film, work)",2],["一点","yì diǎn","a little, a bit",1],
  ["一年","yì nián","one year",1],["一样","yí yàng","the same, alike",1],
  ["一本","yì běn","one (book)",1],["一句","yí jù","one (sentence, line)",2],
  ["一天","yì tiān","one day",1],["一份","yí fèn","one (job, portion, copy)",2],
  ["一条","yì tiáo","one (long thin thing; rule)",2],["一周","yì zhōu","one week",2],
  ["一项","yí xiàng","one (item, project)",3],["一些","yì xiē","some, a few",1],
  ["一场","yì chǎng","one (event, match, storm)",2],["一家","yì jiā","one (company, shop)",2],
  ["一切","yí qiè","everything, all",2],["一部分","yí bù fen","a part of",2],
  ["一生","yì shēng","a whole life",2],["两个","liǎng gè","two",1],
  ["两个人","liǎng gè rén","two people",1],["这个","zhè ge","this one",1],
  ["那个","nà ge","that one",1],["这","zhè","this",1],["那","nà","that",1],
  ["另一个","lìng yí gè","another one",2],["同一个","tóng yí gè","the same one",2],
  ["十几岁","shí jǐ suì","teenage",3],["十年","shí nián","ten years, a decade",1],

  /* ---- verbs the corpus leans on ---- */
  ["让","ràng","to let, to make (someone do)",1],["使","shǐ","to make, to cause",3],
  ["起来","qǐ lái","(to start doing); to get up",2],["下来","xià lái","(to come down; to keep going)",2],
  ["出来","chū lái","to come out",2],["进行","jìn xíng","to carry out, to conduct",3],
  ["使用","shǐ yòng","to use",2],["购买","gòu mǎi","to purchase",3],
  ["获得","huò dé","to obtain, to gain",3],["取得","qǔ dé","to achieve, to obtain",3],
  ["提供","tí gōng","to provide",3],["收到","shōu dào","to receive",2],
  ["受到","shòu dào","to receive, to be subjected to",3],["承担","chéng dān","to bear, to take on",3],
  ["保护","bǎo hù","to protect",2],["伤害","shāng hài","to harm; harm",3],
  ["限制","xiàn zhì","to limit; limit",3],["惩罚","chéng fá","to punish; punishment",3],
  ["控制","kòng zhì","to control",3],["管理","guǎn lǐ","to manage; management",3],
  ["安排","ān pái","to arrange; arrangement",2],["完成","wán chéng","to complete",2],
  ["实践","shí jiàn","to put into practice; practice",4],["参与","cān yù","to participate in",3],
  ["投票","tóu piào","to vote",3],["赞成","zàn chéng","to approve of, to be in favour",3],
  ["欣赏","xīn shǎng","to appreciate, to enjoy",3],["享受","xiǎng shòu","to enjoy",2],
  ["追求","zhuī qiú","to pursue",3],["放弃","fàng qì","to give up",2],
  ["浪费","làng fèi","to waste",2],["减少","jiǎn shǎo","to reduce",3],
  ["增加","zēng jiā","to increase",2],["吸引","xī yǐn","to attract",3],
  ["理解","lǐ jiě","to understand",2],["解释","jiě shì","to explain",2],
  ["建议","jiàn yì","to suggest; suggestion",2],["定义","dìng yì","to define; definition",3],
  ["表现","biǎo xiàn","to show, to perform; performance",3],
  ["意味","yì wèi","to mean, to signify",3],["意味着","yì wèi zhe","to mean that",3],
  ["产生","chǎn shēng","to produce, to give rise to",3],["设计","shè jì","to design; design",3],
  ["反应","fǎn yìng","to react; reaction",3],["撒谎","sā huǎng","to tell a lie",3],
  ["打电话","dǎ diàn huà","to make a phone call",1],["感兴趣","gǎn xìng qù","to be interested in",2],
  ["见过","jiàn guò","to have seen (before)",1],["见","jiàn","to see, to meet",1],
  ["扮演","bàn yǎn","to play (a role)",4],["纪念","jì niàn","to commemorate; memorial",3],
  ["怀孕","huái yùn","to be pregnant",3],["出生","chū shēng","to be born",2],
  ["成长","chéng zhǎng","to grow up; growth",3],["养","yǎng","to raise, to bring up",2],
  ["收养","shōu yǎng","to adopt (a child)",4],["区分","qū fēn","to distinguish",4],

  /* ---- nouns the corpus leans on ---- */
  ["活动","huó dòng","activity, event",2],["行为","xíng wéi","behaviour, conduct",3],
  ["电话","diàn huà","telephone; phone call",1],["电子","diàn zǐ","electronic",2],
  ["电子邮件","diàn zǐ yóu jiàn","email",2],["邮件","yóu jiàn","mail, email",2],
  ["互联网","hù lián wǎng","the internet",2],["媒体","méi tǐ","media",3],
  ["广告","guǎng gào","advertisement",2],["报纸","bào zhǐ","newspaper",2],
  ["杂志","zá zhì","magazine",2],["内容","nèi róng","content",2],
  ["名字","míng zì","name",1],["名人","míng rén","celebrity, famous person",2],
  ["角色","jué sè","role, character",3],["记忆","jì yì","memory",3],
  ["时刻","shí kè","moment",3],["时期","shí qī","period, phase",3],
  ["场所","chǎng suǒ","venue, place",4],["派对","pài duì","party",2],
  ["娱乐","yú lè","entertainment",2],["乐队","yuè duì","band",2],
  ["歌","gē","song",1],["歌曲","gē qǔ","song",2],["艺术","yì shù","art",2],
  ["比赛","bǐ sài","match, competition",1],["设备","shè bèi","device, equipment",3],
  ["产品","chǎn pǐn","product",3],["服务","fú wù","service",2],
  ["企业","qǐ yè","enterprise, business",3],["员工","yuán gōng","employee, staff",3],
  ["办公室","bàn gōng shì","office",2],["项目","xiàng mù","project, item",3],
  ["经济","jīng jì","economy; economic",3],["福利","fú lì","welfare, benefits",4],
  ["医疗","yī liáo","medical care",3],["保险","bǎo xiǎn","insurance",3],
  ["食品","shí pǐn","food (as a product)",2],["毒品","dú pǐn","drugs (narcotics)",4],
  ["生命","shēng mìng","life (biological)",3],["儿童","ér tóng","children",3],
  ["青少年","qīng shào nián","teenager, young person",3],["陌生人","mò shēng rén","stranger",2],
  ["彼此","bǐ cǐ","each other",3],["面前","miàn qián","in front of",2],
  ["身上","shēn shàng","on one's person; about someone",2],
  ["机构","jī gòu","institution, organisation",4],["组织","zǔ zhī","organisation; to organise",3],
  ["公民","gōng mín","citizen",3],["联邦","lián bāng","federal",4],
  ["主义","zhǔ yì","-ism, doctrine",4],["信念","xìn niàn","conviction, belief",4],
  ["圣经","shèng jīng","the Bible",4],["程度","chéng dù","degree, extent",3],
  ["品质","pǐn zhì","quality (of character)",4],["特质","tè zhì","trait, quality",4],
  ["状态","zhuàng tài","state, condition",3],["议题","yì tí","issue, topic",4],
  ["成就","chéng jiù","achievement",3],["困难","kùn nán","difficulty; difficult",2],
  ["背景","bèi jǐng","background",3],["过程","guò chéng","process",3],
  ["顺序","shùn xù","order, sequence",3],["声音","shēng yīn","sound, voice",2],
  ["信心","xìn xīn","confidence",3],["恐怖","kǒng bù","terror; terrifying",4],
  ["性行为","xìng xíng wéi","sexual behaviour",4],["性关系","xìng guān xì","sexual relationship",4],

  /* ---- describing, judging, hedging ---- */
  ["分别","fēn bié","respectively; to distinguish",3],["相比","xiāng bǐ","compared with",3],
  ["总体","zǒng tǐ","overall",3],["总的来说","zǒng de lái shuō","on the whole",3],
  ["直接","zhí jiē","direct, directly",2],["通过","tōng guò","through, by means of",2],
  ["重新","chóng xīn","again, anew",3],["同时","tóng shí","at the same time",2],
  ["目前","mù qián","at present, currently",3],["平时","píng shí","usually, in normal times",2],
  ["永远","yǒng yuǎn","forever",2],["差不多","chà bu duō","about the same, more or less",2],
  ["合法","hé fǎ","legal, lawful",3],["违法","wéi fǎ","illegal, to break the law",4],
  ["合理","hé lǐ","reasonable",3],["严格","yán gé","strict",3],
  ["宽容","kuān róng","tolerant; tolerance",4],["主动","zhǔ dòng","proactive, on one's own initiative",3],
  ["亲密","qīn mì","intimate, close",3],["亲近","qīn jìn","close (to someone)",3],
  ["浪漫","làng màn","romantic",2],["流行","liú xíng","popular, in fashion",2],
  ["轻松","qīng sōng","relaxed, easy",2],["完美","wán měi","perfect",2],
  ["明显","míng xiǎn","obvious",3],["固定","gù dìng","fixed, regular",3],
  ["私人","sī rén","private, personal",3],["重大","zhòng dà","major, significant",3],
  ["度假","dù jià","to take a holiday",2],["感受","gǎn shòu","to feel; impression",3],
  ["体会","tǐ huì","to appreciate from experience",4],["公立","gōng lì","publicly run (school)",4],
/* ---- second pass: the words the segmenter was still splitting ---- */
  ["时","shí","time; when",1],["得","de","(links a verb to how it is done)",2],["当","dāng","when; to serve as",2],
  ["当你","dāng nǐ","when you",1],["当年","dāng nián","back then, in those days",3],
  ["脑子","nǎo zi","mind, head",2],["自在","zì zài","at ease, comfortable",3],
  ["之外","zhī wài","outside of, besides",3],["行动","xíng dòng","action; to act",3],
  ["亲眼","qīn yǎn","with one's own eyes",3],["亲手","qīn shǒu","with one's own hands",3],
  ["亲生","qīn shēng","biological (parent, child)",4],["子女","zǐ nǚ","sons and daughters, children",3],
  ["身边","shēn biān","around one, close by",2],["晚上","wǎn shàng","evening",1],
  ["生日","shēng rì","birthday",1],["节日","jié rì","festival, holiday",2],
  ["聚会","jù huì","gathering, get-together",2],["购物","gòu wù","shopping",2],
  ["商店","shāng diàn","shop",1],["社区","shè qū","community",3],
  ["公众","gōng zhòng","the public",3],["领域","lǐng yù","field, domain",4],
  ["军队","jūn duì","the military",3],["警察","jǐng chá","police",2],
  ["政党","zhèng dǎng","political party",4],["竞选","jìng xuǎn","to run for office",4],
  ["移民","yí mín","immigration; immigrant",4],["公民权","gōng mín quán","civil rights",4],
  ["规则","guī zé","rule",3],["规定","guī dìng","regulation; to stipulate",3],
  ["制度化","zhì dù huà","institutionalised",4],["监管","jiān guǎn","regulation, oversight",4],
  ["强制","qiáng zhì","compulsory, to compel",4],["措施","cuò shī","measure, step",4],
  ["原则","yuán zé","principle",3],["立场","lì chǎng","position, stance",4],
  ["判断","pàn duàn","to judge; judgement",3],["研究","yán jiū","research; to research",3],
  ["结果","jié guǒ","result; as a result",2],["原因","yuán yīn","reason, cause",2],
  ["错误","cuò wù","mistake; wrong",2],["冲突","chōng tū","conflict",3],
  ["避免","bì miǎn","to avoid",3],["应对","yìng duì","to cope with, to respond to",4],
  ["采取","cǎi qǔ","to adopt (a measure)",4],["改善","gǎi shàn","to improve",3],
  ["坚持","jiān chí","to persist, to stick with",3],["独立","dú lì","independent",3],
  ["建立","jiàn lì","to build, to establish",3],["培养","péi yǎng","to cultivate, to bring up",3],
  ["投入","tóu rù","to put into; committed",3],["负责","fù zé","to be responsible for",3],
  ["担任","dān rèn","to hold (a post)",4],["职位","zhí wèi","position, post",3],
  ["毕业","bì yè","to graduate",2],["课程","kè chéng","course, subject",2],
  ["任务","rèn wù","task",2],["办公","bàn gōng","to work (in an office)",3],
  ["商业","shāng yè","business, commercial",3],["认同","rèn tóng","to identify with; identification",4],
  ["评价","píng jià","to assess; assessment",3],["注意","zhù yì","to notice, to pay attention",2],
  ["记住","jì zhù","to remember, to memorise",2],["认真","rèn zhēn","serious, conscientious",2],
  ["尽量","jǐn liàng","as far as possible",3],["反而","fǎn ér","on the contrary, instead",3],
  ["无法","wú fǎ","unable to",3],["绝不","jué bù","absolutely not",3],
  ["彻底","chè dǐ","thorough, completely",3],["深刻","shēn kè","deep, profound",3],
  ["平静","píng jìng","calm",3],["失望","shī wàng","disappointed",2],
  ["遗憾","yí hàn","regret; a pity",3],["欢迎","huān yíng","to welcome",1],
  ["相似","xiāng sì","similar",3],["属于","shǔ yú","to belong to",3],
  ["具备","jù bèi","to possess (qualities)",4],["恢复","huī fù","to recover, to restore",3],
  ["度过","dù guò","to spend (time), to get through",3],["收藏","shōu cáng","to collect; a collection",3],
  ["风格","fēng gé","style",3],["外貌","wài mào","appearance, looks",3],
  ["气味","qì wèi","smell",3],["声望","shēng wàng","reputation, standing",4],
  ["现场","xiàn chǎng","in person, on the scene",3],["时代","shí dài","era, age",3],
  ["幻想","huàn xiǎng","fantasy; to fantasise",4],["意思","yì si","meaning; interest",1],
  ["演员","yǎn yuán","actor",2],["明星","míng xīng","star, celebrity",2],
  ["唱歌","chàng gē","to sing",1],["首歌","shǒu gē","a song (measure + noun)",2],
  ["赛事","sài shì","sporting event",4],["球","qiú","ball",1],
  ["纸质","zhǐ zhì","print, paper (format)",4],["全国","quán guó","nationwide",3],
  ["分钟","fēn zhōng","minute",1],["五年","wǔ nián","five years",1],
  ["五个","wǔ gè","five",1],["负面","fù miàn","negative",3],
  ["同性","tóng xìng","same-sex",4],["未婚","wèi hūn","unmarried",4],
  ["婚前","hūn qián","before marriage",4],["婚礼","hūn lǐ","wedding",3],
  ["婴儿","yīng ér","baby, infant",3],["堕胎","duò tāi","abortion",4],
  ["自杀","zì shā","suicide",4],["成瘾","chéng yǐn","addiction, to become addicted",4],
  ["枪支","qiāng zhī","firearms",4],["祖先","zǔ xiān","ancestors",4],
  ["调情","tiáo qíng","to flirt",4],["加入","jiā rù","to join",2],
  ["有生之年","yǒu shēng zhī nián","in one's lifetime",4],["大多数","dà duō shù","most, the majority",2],
/* ---- third pass: the topic words the first two were still splitting ---- */
  ["徒步","tú bù","to hike; hiking",2],["散步","sàn bù","to go for a walk",1],
  ["休闲","xiū xián","leisure",3],["独处","dú chǔ","to be on one's own",4],
  ["所在","suǒ zài","where something is; location",4],["场合","chǎng hé","occasion, setting",3],
  ["早上","zǎo shàng","morning",1],["下午","xià wǔ","afternoon",1],
  ["网站","wǎng zhàn","website",2],["视频","shì pín","video",2],
  ["信息","xìn xī","information",2],["工具","gōng jù","tool",2],
  ["表演","biǎo yǎn","to perform; performance",2],["演出","yǎn chū","a show, a performance",3],
  ["舞台","wǔ tái","stage",3],["乐器","yuè qì","musical instrument",3],
  ["挑战","tiǎo zhàn","challenge; to challenge",3],["申请","shēn qǐng","to apply for",3],
  ["现实","xiàn shí","reality; realistic",3],["真实","zhēn shí","real, genuine",3],
  ["心情","xīn qíng","mood",2],["情绪","qíng xù","emotion, mood",3],
  ["精神","jīng shén","spirit; mental",3],["道理","dào lǐ","reason, sense",2],
  ["理由","lǐ yóu","reason, grounds",2],["因素","yīn sù","factor",4],
  ["条件","tiáo jiàn","condition, requirement",3],["规模","guī mó","scale, size",4],
  ["具体","jù tǐ","specific, concrete",3],["基本","jī běn","basic; basically",2],
  ["之类","zhī lèi","and the like",3],["无论","wú lùn","no matter, regardless",3],
  ["再也","zài yě","never again (with 不/没)",3],["瞬间","shùn jiān","an instant",4],
  ["提前","tí qián","in advance, ahead of time",3],["留下","liú xià","to leave behind, to keep",2],
  ["保存","bǎo cún","to preserve, to keep",3],["整理","zhěng lǐ","to tidy, to sort out",2],
  ["寻找","xún zhǎo","to look for, to seek",3],["进入","jìn rù","to enter",2],
  ["鼓励","gǔ lì","to encourage",3],["重视","zhòng shì","to attach importance to",3],
  ["刺激","cì jī","exciting; to stimulate",3],["潮流","cháo liú","trend",4],
  ["运气","yùn qì","luck",2],["麻烦","má fán","trouble; troublesome",2],
  ["障碍","zhàng ài","obstacle, barrier",4],["秘密","mì mì","secret",3],
  ["背叛","bèi pàn","to betray; betrayal",4],["原本","yuán běn","originally",3],
  ["英雄","yīng xióng","hero",3],["称呼","chēng hū","to address (someone); a form of address",3],
  ["体系","tǐ xì","system",4],  ["薪水","xīn shuǐ","salary",3],["劳动","láo dòng","labour, work",3],
  ["公职","gōng zhí","public office",4],["候选","hòu xuǎn","candidate (as modifier)",4],
  ["歧视","qí shì","discrimination; to discriminate",4],["骚扰","sāo rǎo","harassment; to harass",4],
  ["族裔","zú yì","ethnic group",4],["严厉","yán lì","severe, harsh",4],
  ["戒掉","jiè diào","to give up (a habit)",4],["裸体","luǒ tǐ","naked; nudity",4],
  ["俱乐部","jù lè bù","club",3],["团体","tuán tǐ","group, team",3],
  ["游乐","yóu lè","amusement, recreation",4],["预测","yù cè","to predict",4],
  ["熟悉","shú xī","familiar with",2],["熟练","shú liàn","proficient, fluent",3],
  ["掌握","zhǎng wò","to master, to have a command of",3],["卡片","kǎ piàn","card",2],
  ["贷款","dài kuǎn","loan; to take out a loan",3],  ["折扣","zhé kòu","discount",3],["答应","dā ying","to agree, to say yes",2],
  ["议会","yì huì","parliament",4],["议员","yì yuán","member of parliament",4],
  ["立法","lì fǎ","legislation",4],
  ["外交","wài jiāo","diplomacy",4],["税","shuì","tax",3],
  ["恐怖分子","kǒng bù fèn zǐ","terrorist",4],["反恐","fǎn kǒng","counter-terrorism",4],
  ["监控","jiān kòng","surveillance; to monitor",4],["开支","kāi zhī","expenditure",4],
  ["差距","chā jù","gap, disparity",4],["贫富","pín fù","rich and poor",4],
  ["扩大","kuò dà","to widen, to expand",3],["元首","yuán shǒu","head of state",4],
  ["校歌","xiào gē","school song",4],["课外","kè wài","extracurricular",3],
  ["奖学金","jiǎng xué jīn","scholarship",4],["招募","zhāo mù","to recruit",4],
  ["报酬","bào chóu","payment, remuneration",4],["冠军","guàn jūn","champion, title",3],
  ["季后赛","jì hòu sài","play-offs",4],["位置","wèi zhì","position, place",2],
  ["球队","qiú duì","team (ball sport)",2],["业余","yè yú","amateur",3],
  ["足球","zú qiú","football",1],["篮球","lán qiú","basketball",1],
  ["极限","jí xiàn","extreme; limit",4],["滑雪","huá xuě","to ski",3],
  ["主持人","zhǔ chí rén","host, presenter",3],["高估","gāo gū","to overrate",4],
  ["有机","yǒu jī","organic",3],["快餐","kuài cān","fast food",2],
  ["辣","là","spicy, hot",1],["甜","tián","sweet",1],["咸","xián","salty",2],
  ["自传","zì zhuàn","autobiography",4],["传记","zhuàn jì","biography",4],
  ["小说","xiǎo shuō","novel, fiction",2],["情节","qíng jié","plot",3],
  ["玩具","wán jù","toy",2],
  ["回收","huí shōu","to recycle",3],["垃圾","lā jī","rubbish",2],
  ["截止","jié zhǐ","cut-off, deadline",4],
  ["振作","zhèn zuò","to cheer up, to pull oneself together",4],
  ["低落","dī luò","low (in spirits)",4],    ["成名","chéng míng","to become famous",4],["同学会","tóng xué huì","school reunion",4],
  ["教授","jiào shòu","professor",3],
  ["寒假","hán jià","winter holiday",2],["暑假","shǔ jià","summer holiday",2],
/* ---- fourth pass: the connective vocabulary the model answers run on ----
     These are the words that hold a two-minute answer together rather than the
     words it is about. 而不是 and 之所以 do more work in a spoken answer than
     any noun in it, and they were the largest gap in the bank. */
  ["而","ér","and yet; while (formal link)",2],
  ["而是","ér shì","but rather",2],["而不是","ér bú shì","rather than, and not",2],
  ["之所以","zhī suǒ yǐ","the reason why ... is",3],
  ["与其说","yǔ qí shuō","rather than saying (it is A)",4],
  ["不如说","bù rú shuō","it would be truer to say",4],
  ["之后","zhī hòu","after, afterwards",2],["之前","zhī qián","before",2],
  ["之内","zhī nèi","within",3],["以来","yǐ lái","since",3],
  ["恰恰","qià qià","precisely, exactly",3],["正是","zhèng shì","it is precisely",3],
  ["确实","què shí","indeed, certainly",2],["的确","dí què","indeed",3],
  ["实际","shí jì","actual, in practice",3],
  ["实际上","shí jì shàng","in fact, in practice",3],
  ["老实说","lǎo shí shuō","to be honest",2],["老实","lǎo shí","honest, frank",2],
  ["说实话","shuō shí huà","honestly speaking",2],
    ["换句话说","huàn jù huà shuō","in other words",3],
  ["也就是说","yě jiù shì shuō","that is to say",3],
  ["并不","bìng bù","not at all (contrary to expectation)",3],
  ["毫无","háo wú","not the slightest",4],["丝毫","sī háo","in the slightest",4],
  ["根本","gēn běn","at all; fundamental",2],  ["相当","xiāng dāng","quite, fairly",3],["稍微","shāo wēi","slightly",3],
  ["至于","zhì yú","as for",3],
  ["随时","suí shí","at any time",3],["默认","mò rèn","to assume by default; default",4],
  ["唯一","wéi yī","the only",2],["同样","tóng yàng","likewise, the same",2],
  ["同一","tóng yī","the same (one)",2],["别的","bié de","other, else",1],
  ["整个","zhěng gè","the whole",2],["共同","gòng tóng","shared, in common",3],
  ["互相","hù xiāng","each other, mutually",2],  ["区别","qū bié","difference; to distinguish",2],
  ["版本","bǎn běn","version",3],["形状","xíng zhuàng","shape",3],
  ["答案","dá àn","answer",2],["标准","biāo zhǔn","standard, criterion",3],
  ["例子","lì zi","example",2],["证明","zhèng míng","to prove; proof",3],
  ["可靠","kě kào","reliable",3],["确定","què dìng","certain; to confirm",2],
  ["清楚","qīng chǔ","clear, clearly",1],["意外","yì wài","unexpected; surprise",2],
  ["结论","jié lùn","conclusion",3],["观察","guān chá","to observe",3],
  ["承受","chéng shòu","to bear, to withstand",4],["消耗","xiāo hào","to consume, to drain",4],
  ["代价","dài jià","cost, price paid",3],["成本","chéng běn","cost",3],
  ["回报","huí bào","return, payoff",3],  ["放在","fàng zài","to put (somewhere)",1],  ["连着","lián zhe","consecutively, in a row",3],
  ["逐渐","zhú jiàn","gradually",3],["渐渐","jiàn jiàn","gradually",3],
  ["从此","cóng cǐ","from then on",3],
  ["此外","cǐ wài","besides, in addition",4],  ["否则","fǒu zé","otherwise",3],
  ["即使","jí shǐ","even if",3],["哪怕","nǎ pà","even if",3],
  ["除非","chú fēi","unless",3],["只要","zhǐ yào","as long as",2],
  ["不得不","bù dé bù","to have no choice but to",3],
  ["二十","èr shí","twenty",1],["三十","sān shí","thirty",1],["四十","sì shí","forty",1],
  ["第二","dì èr","second",1],["第三","dì sān","third",1],
  ["左右","zuǒ yòu","approximately, about",2],["大约","dà yuē","approximately",2],
  ["以上","yǐ shàng","above, more than",2],["以下","yǐ xià","below, less than",2]

  ]
};
